# Generated by Django 5.2.10 on 2026-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_time_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtimetask',
            options={'ordering': ['-create_at'], 'verbose_name': '长耗时任务', 'verbose_name_plural': '长耗时任务'},
        ),
        migrations.RemoveField(
            model_name='longtimetask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='longtimetask',
            name='user',
        ),
        migrations.AddField(
            model_name='longtimetask',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Celery任务ID'),
        ),
        migrations.AddField(
            model_name='longtimetask',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始执行时间'),
        ),
        migrations.AddField(
            model_name='longtimetask',
            name='state',
            field=models.CharField(choices=[('PENDING', '等待执行'), ('RUNNING', '正在执行'), ('FINISHED', '已完成'), ('FAILED', '执行失败')], db_index=True, default='PENDING', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='任务结果'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='task_params',
            field=models.TextField(default='{}', verbose_name='任务参数'),
        ),
        migrations.AlterField(
            model_name='longtimetask',
            name='task_type',
            field=models.CharField(db_index=True, max_length=100, verbose_name='任务类型'),
        ),
        migrations.AddIndex(
            model_name='longtimetask',
            index=models.Index(fields=['state', 'create_at'], name='long_time_t_state_01421a_idx'),
        ),
        migrations.AddIndex(
            model_name='longtimetask',
            index=models.Index(fields=['task_type', 'state'], name='long_time_t_task_ty_ed1779_idx'),
        ),
        migrations.AlterModelTable(
            name='longtimetask',
            table='long_time_task',
        ),
    ]
