"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q(9@&$f-8t(h9k167f+hu5nmfr$4u20wi8j1dt7moz6%0%ori4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "long_time_task",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "demo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============== Celery 配置 ==============

# Broker 配置 (Redis)
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"

# 序列化配置
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# 时区配置
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = True

# Worker 配置
CELERY_WORKER_CONCURRENCY = 4  # 并发worker数
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 预取任务数
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # 每个worker处理的最大任务数

# 任务配置
CELERY_TASK_SOFT_TIME_LIMIT = 3300  # 软超时 (秒)
CELERY_TASK_TIME_LIMIT = 3600  # 硬超时 (秒)
CELERY_TASK_ACKS_LATE = True  # 任务完成后确认
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # worker丢失时拒绝任务

# 重试配置
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 默认重试延迟
CELERY_TASK_MAX_RETRIES = 3  # 默认最大重试次数

# 结果配置
CELERY_RESULT_EXPIRES = 86400  # 结果过期时间 (24小时)
CELERY_TASK_TRACK_STARTED = True  # 跟踪任务开始状态

# 任务路由配置
CELERY_TASK_ROUTES = {
    "long_time_task.celery_tasks.execute_long_time_task": {"queue": "default"},
}

# 队列配置
CELERY_TASK_QUEUES = {
    "default": {
        "exchange": "default",
        "routing_key": "default",
    },
    "heavy": {
        "exchange": "heavy",
        "routing_key": "heavy",
    },
    "priority": {
        "exchange": "priority",
        "routing_key": "priority",
    },
}

# 任务优先级
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "priority_steps": list(range(10)),
    "sep": ":",
    "queue_order_strategy": "priority",
}
